#!/usr/bin/python3

import io, json, os

from pydaten.node import Node
from pydaten.address import Address

import argparse

DEFAULT_IP = '0.0.0.0'
DEFAULT_PORT = 32323
DEFAULT_INITIAL_PEERS = ['http://{}:{}'.format(DEFAULT_IP, DEFAULT_PORT)]

if __name__ == '__main__':
    CONFIG_DIR = os.path.join(os.path.expanduser("~"), '.daten')
    if not os.path.exists(CONFIG_DIR):
        os.makedirs(CONFIG_DIR)
    CONFIG_PATH = os.path.join(CONFIG_DIR, 'node.json')

    try:
        with io.open(CONFIG_PATH, 'r') as f:
            config = json.load(f)
    except IOError:
        config = {'ip': DEFAULT_IP,
                  'port': DEFAULT_PORT,
                  'path': os.path.join(CONFIG_DIR, 'data'),
                  'initialPeers': DEFAULT_INITIAL_PEERS}
        with io.open(CONFIG_PATH, 'w') as f:
            json.dump(config, f, indent = 2)

    parser = argparse.ArgumentParser()
    parser.add_argument("--host", help="Host of the node.")
    parser.add_argument("--port", help="Port of the node.")
    parser.add_argument("--path", help="Path for storing blocks.")
    parser.add_argument("--init", help="Initial peer.")
    args = parser.parse_args()

    node = Node(args.host or config['ip'],
                args.port or config['port'],
                args.path or config['path'],
                {args.init} or config['initialPeers'])
